### ISSUE TITLE
Make the package go gettable 

### ISSUE THREAD

**Issue by ryadzenine** [ivpusic/go-hotreload#2]
Hi there, 
   The organisation of the code in you package is not usual. Therefore, a simple go get does not work.

* First, go get can't find any package to build  

`package github.com/ivpusic/go-hotreload
        imports github.com/ivpusic/go-hotreload
        imports github.com/ivpusic/go-hotreload: no buildable Go source files in
 /home/ryad/workspace/go/src/github.com/ivpusic/go-hotreload`

* Second, when i go to your package directory i have and try to build your program i have:

`hr.go:4:2: cannot find package "github.com/ivpusic/golog" in any of:
        /usr/local/go/src/github.com/ivpusic/golog (from $GOROOT)
        /home/ryad/workspace/go/src/github.com/ivpusic/golog (from $GOPATH)
hr.go:5:2: cannot find package "gopkg.in/alecthomas/kingpin.v1" in any of:
        /usr/local/go/src/gopkg.in/alecthomas/kingpin.v1 (from $GOROOT)
        /home/ryad/workspace/go/src/gopkg.in/alecthomas/kingpin.v1 (from $GOPATH
)
hr.go:6:2: cannot find package "gopkg.in/fsnotify.v1" in any of:
        /usr/local/go/src/gopkg.in/fsnotify.v1 (from $GOROOT)
        /home/ryad/workspace/go/src/gopkg.in/fsnotify.v1 (from $GOPATH)`

**Comment by ivpusic** [comment]
What about ``go get github.com/ivpusic/go-hotreload/hr``? It is on readme page.

Library is called go-hotreload, and command which exposes is ``hr``. I know that name of library is bad :D, but now is maybe to late to change it.

**Comment by ryadzenine** [comment]
Well that works, but it does not follow the conventions of the community.  
Most of the golang devs will expect a go get on the repo to just work. like i did.

**Comment by ivpusic** [comment]
You are right. I am aware of that fact. Don't know if it is better to leave it like this, or to change name of library to something better (where library name and command which library exposes are the same).

**Comment by ryadzenine** [comment]
I suggest you stick with the conventions, the community really values that. Thus, you might consider changing the name of the library. 
Good luck.

**Comment by ivpusic** [comment]
Yes, I suppose that is good idea. As you know naming is bitch, do you have some cool suggestion for name? :D

**Comment by ryadzenine** [comment]
i am very found of references, i would call it bebop as in cowboy bebop.
