### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by EtienneBruines** [ivpusic/go-hotreload#3]
You may want to use [fsnotify](https://github.com/go-fsnotify/fsnotify) to be compatible across platforms (instead of the `.bat` file)

**Comment by ivpusic** [comment]
Library is already using fsnotify https://github.com/ivpusic/go-hotreload/blob/master/hr/hr.go#L6, and it is already cross-plarform compatibile (Linux, OSX, Windows).

``.bat`` file is used for getting pid of process which is running on port X (for windows).
