### ISSUE TITLE
execute multiple commands with &

### ISSUE THREAD

**Issue by prabirshrestha** [ivpusic/go-hotreload#4]
`hr` currently doesn't seem to support chaining commands with `&`

```bash
hr -c "go build & ./server"
```

**Comment by ivpusic** [comment]
Currently it is not my top priority. One workaround is to put multiple commands in single script, and then execute that script. If you are interested in PR, they are welcome.

**Comment by ivpusic** [comment]
Fixed by https://github.com/ivpusic/go-hotreload/pull/6
